import { BackgroundPreset } from '../types';

export const BACKGROUND_PRESETS: BackgroundPreset[] = [
  {
    id: 'bg-mahogany-office',
    title: 'Executive Corner Mahogany Office',
    titleAr: 'مكتب تمليك خشب الماهوجني الفاخر',
    category: 'Corporate',
    location: 'High-Rise Office Tower',
    lightingStyle: 'Warm Ambient Studio',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'soft-bokeh',
  },
  {
    id: 'bg-difc-dubai-skyline',
    title: 'Dubai DIFC Skyline Glass Atrium',
    titleAr: 'أفق دبي المالي والمباني الزجاجية',
    category: 'City Skyline',
    location: 'Dubai, UAE',
    lightingStyle: 'Natural Daylight',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'heavy-bokeh',
  },
  {
    id: 'bg-tech-loft-glass',
    title: 'Architectural Tech Loft & Glass Partition',
    titleAr: 'مساحة عمل تقنية زجاجية عصرية',
    category: 'Modern Workspace',
    location: 'San Francisco / London',
    lightingStyle: 'Cool Daylight LED',
    image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'soft-bokeh',
  },
  {
    id: 'bg-law-library',
    title: 'Classic Leather & Oak Law Library',
    titleAr: 'مكتبة حقوقية خشبية كلاسيكية',
    category: 'Academic & Legal',
    location: 'University / Inns of Court',
    lightingStyle: 'Warm Directional Lamp',
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'soft-bokeh',
  },
  {
    id: 'bg-studio-neutral-slate',
    title: 'Minimal Seamless Studio Slate Grey',
    titleAr: 'خلفية استوديو رمادية رمادية محايدة',
    category: 'Studio Solid',
    location: 'Portrait Studio',
    lightingStyle: 'Balanced Softbox',
    image: 'https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'sharp',
  },
  {
    id: 'bg-nyc-financial-district',
    title: 'Manhattan Financial Skyline Bokeh',
    titleAr: 'أفق نيويورك المالي بوكيه سينمائي',
    category: 'City Skyline',
    location: 'New York City',
    lightingStyle: 'Sunset Golden Hour',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'heavy-bokeh',
  },
  {
    id: 'bg-modern-medical-atrium',
    title: 'Bright Clinical Medical Atrium',
    titleAr: 'ممر ومركز طبي استشاري حديث',
    category: 'Healthcare',
    location: 'University Hospital',
    lightingStyle: 'Crisp White Diffuse',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'soft-bokeh',
  },
  {
    id: 'bg-luxury-penthouse-terrace',
    title: 'Penthouse Terrace & City Lights',
    titleAr: 'شرفة بنتهاوس فاخر مع أضواء المدينة',
    category: 'Luxury',
    location: 'Tokyo / Singapore',
    lightingStyle: 'Twilight Rim Light',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=600&q=80',
    blurLevel: 'heavy-bokeh',
  }
];
