import { OutfitPreset } from '../types';

export const OUTFIT_PRESETS: OutfitPreset[] = [
  {
    id: 'outfit-executive-navy-suit',
    title: 'Executive Navy Tailored Suit',
    titleAr: 'بدلة كحيلة رسمية مفصلة',
    category: 'Executive',
    gender: 'unisex',
    colorOptions: ['Midnight Navy', 'Charcoal Grey', 'Deep Indigo', 'Jet Black'],
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'executive',
  },
  {
    id: 'outfit-royal-bisht-shemagh',
    title: 'Royal Gold-Trimmed Bisht & Shemagh',
    titleAr: 'البشت الملكي المقصب والشماغ السعودي',
    category: 'Cultural',
    gender: 'male',
    colorOptions: ['Black & Gold', 'Cream & Gold', 'Brown & Gold', 'Navy & Silver'],
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'cultural',
  },
  {
    id: 'outfit-casual-blazer-black',
    title: 'Silicon Valley Wool Blazer & Shirt',
    titleAr: 'بليزر صوف عصري - وادي السيليكون',
    category: 'Tech',
    gender: 'unisex',
    colorOptions: ['Matte Black', 'Heather Grey', 'Navy Blue', 'Forest Green'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'business-casual',
  },
  {
    id: 'outfit-doctor-labcoat',
    title: 'Clinical Lab Coat & Stethoscope',
    titleAr: 'المعطف الطبي والاستشاري مع السماعة',
    category: 'Medical',
    gender: 'unisex',
    colorOptions: ['Pristine White', 'Medical Teal', 'Surgeon Navy'],
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'specialized',
  },
  {
    id: 'outfit-pilot-uniform',
    title: 'Aviation Captain Epaulet Uniform',
    titleAr: 'زي قبطان الطيران بالرتب الذهبية',
    category: 'Aviation',
    gender: 'unisex',
    colorOptions: ['Dark Navy & Gold', 'Midnight Black & Gold'],
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'specialized',
  },
  {
    id: 'outfit-womens-power-suit',
    title: 'Silk Blouse & Structured Power Suit',
    titleAr: 'بدلة رسمية نسائية مع بلوزة حريرية',
    category: 'Executive',
    gender: 'female',
    colorOptions: ['Emerald Green', 'Royal Navy', 'Ivory Cream', 'Burgundy Wine'],
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'executive',
  },
  {
    id: 'outfit-emirati-kandora',
    title: 'Emirati Pristine White Kandora',
    titleAr: 'الكندورة الإماراتية النواعية الفاخرة',
    category: 'Cultural',
    gender: 'male',
    colorOptions: ['Pristine White', 'Soft Sand', 'Charcoal Grey'],
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'cultural',
  },
  {
    id: 'outfit-luxury-tuxedo',
    title: 'Black Tie Satin Tuxedo',
    titleAr: 'بدلة التكسيدو الفاخرة لليالي الرسمية',
    category: 'Editorial',
    gender: 'unisex',
    colorOptions: ['Black Satin Lapel', 'Midnight Blue Satin'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'executive',
  },
  {
    id: 'outfit-black-turtleneck-blazer',
    title: 'Cashmere Turtleneck & Italian Blazer',
    titleAr: 'سترة ياقة مرتفعة كشمير وبليزر إيطالي',
    category: 'Creative',
    gender: 'unisex',
    colorOptions: ['All Black', 'Charcoal & Grey', 'Beige & Camel'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'business-casual',
  },
  {
    id: 'outfit-judicial-robe',
    title: 'Judicial Advocate Robe & Gown',
    titleAr: 'روب القضاء والمحاماة الرسمي',
    category: 'Legal',
    gender: 'unisex',
    colorOptions: ['Black Silk Robe', 'Velvet Collar Black'],
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
    formalLevel: 'specialized',
  }
];
