import { HeadshotStyle } from '../types';

export const HEADSHOT_STYLES: HeadshotStyle[] = [
  // C-SUITE & EXECUTIVE
  {
    id: 'ceo-fortune-500',
    title: 'Fortune 500 CEO Portrait',
    titleAr: 'بورتريه الرئيس التنفيذي فورشن 500',
    category: 'c-suite',
    description: 'Commanding executive portrait with deep mahogany corner office backdrop and soft Rembrandt key lighting.',
    descriptionAr: 'بورتريه تنفيذي مهيب مع خلفية مكتب فاخر وإضاءة رامبرانت ناعمة الاحترافية.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-executive-navy-suit',
    recommendedBackground: 'bg-mahogany-office',
    lightingSetup: '3-Point Rembrandt',
    tags: ['CEO', 'Executive', 'Boardroom', 'Leadership'],
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'tech-founder-unicorn',
    title: 'Unicorn Tech Founder',
    titleAr: 'مؤسس شركة تقنية مصلحة',
    category: 'tech',
    description: 'Modern, approachable startup leader with architectural loft background and warm studio rim light.',
    descriptionAr: 'قيادي تقني عصري مع خلفية لوفت معماري وإضاءة استوديو دافئة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-casual-blazer-black',
    recommendedBackground: 'bg-tech-loft-glass',
    lightingSetup: 'Softbox Key + Rim',
    tags: ['Startup', 'Tech', 'Founder', 'Modern'],
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'linkedin-top-voice',
    title: 'LinkedIn Top Voice Leader',
    titleAr: 'قائد وقلم مؤنس على لينكد إن',
    category: 'corporate',
    description: 'High-engagement personal brand headshot with clean neutral gradient background and bright engaging smile.',
    descriptionAr: 'صورة شخصية عالية التفاعل مع خلفية تدرج حيادية محايدة وابتسامة واثقة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-charcoal-suit',
    recommendedBackground: 'bg-studio-neutral-slate',
    lightingSetup: 'Butterfly Beauty',
    tags: ['LinkedIn', 'Personal Brand', 'Corporate', 'Thought Leader'],
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'senior-partner-law',
    title: 'Supreme Court & Law Partner',
    titleAr: 'شريك رئيسي في المحاماة والاستشارات القانونية',
    category: 'legal',
    description: 'Dignified legal authority portrait set against leather-bound law library shelves with crisp directional light.',
    descriptionAr: 'بورتريه قانوني مهيب أمام مكتبة قانونية جلدية فاخرة وإضاءة متوازنة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-double-breasted-black-suit',
    recommendedBackground: 'bg-law-library',
    lightingSetup: 'Split Studio',
    tags: ['Lawyer', 'Legal', 'Supreme Court', 'Senior Partner'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'medical-chief-surgeon',
    title: 'Chief Medical Specialist & Surgeon',
    titleAr: 'رئيس أطباء وجراح استشاري',
    category: 'healthcare',
    description: 'Reassuring, crisp healthcare professional in medical attire with clean clinical background.',
    descriptionAr: 'صورة طبيب استشاري مبعثة للاطمئنان بالزي الطبي الخلفي النظيف.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-doctor-labcoat',
    recommendedBackground: 'bg-modern-medical-atrium',
    lightingSetup: 'Natural Window',
    tags: ['Doctor', 'Surgeon', 'Healthcare', 'Medicine'],
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'investment-banker-wallst',
    title: 'Wall Street Investment Banker',
    titleAr: 'مصرفي استثماري - وول ستريت',
    category: 'finance',
    description: 'Sharp financial strategist portrait with Manhattan financial district bokeh view.',
    descriptionAr: 'بورتريه استراتيجي مالي حاد مع خلفية منطقة وول ستريت المالية.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-pinstripe-suit',
    recommendedBackground: 'bg-nyc-financial-district',
    lightingSetup: '3-Point Rembrandt',
    tags: ['Banker', 'Finance', 'Wall Street', 'Investments'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'saudi-royal-executive',
    title: 'Saudi Royal Bisht & Shemagh Elite',
    titleAr: 'البشت السعودي الفاخر والشماغ الملكي',
    category: 'cultural',
    description: 'Traditional Gulf executive elegance featuring hand-woven gold-trimmed Bisht and pristine Shemagh with luxury interior.',
    descriptionAr: 'أناقة قيادية خليجية بالبشت المذهب والشماغ الأبيض/الأحمر الملكي مع خلفية مجلس فاخر.',
    gender: 'male',
    recommendedOutfit: 'outfit-royal-bisht-shemagh',
    recommendedBackground: 'bg-dubai-royal-palace',
    lightingSetup: 'Butterfly Beauty',
    tags: ['Saudi', 'Bisht', 'Gulf Executive', 'Shemagh', 'KSA'],
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'emirati-kandra-leader',
    title: 'Emirati Abaya & Kandora Leader',
    titleAr: 'الزي الإماراتي القيادي الفاخر',
    category: 'cultural',
    description: 'Sleek UAE leadership style with immaculate white Kandora or embroidered Abaya set against DIFC skyline.',
    descriptionAr: 'طراز قيادي إماراتي رفيع مع الكندورة أو العباية المطرزة خلف أفق مركز دبي المالي.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-emirati-kandora',
    recommendedBackground: 'bg-difc-dubai-skyline',
    lightingSetup: '3-Point Rembrandt',
    tags: ['Emirati', 'Kandora', 'UAE', 'DIFC', 'Dubai'],
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'airline-captain-pilot',
    title: 'Commercial Airline Captain',
    titleAr: 'قبطان طيران تجاري',
    category: 'aviation',
    description: 'Authoritative commercial pilot in uniform with four gold epaulets and tarmac aircraft background.',
    descriptionAr: 'قبطان طيران بالزي الرسمي والرتب الذهبية أمام خلفية مدرج الطائرات.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-pilot-uniform',
    recommendedBackground: 'bg-airport-tarmac-jet',
    lightingSetup: 'Split Studio',
    tags: ['Pilot', 'Captain', 'Aviation', 'Commercial Jet'],
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'creative-art-director',
    title: 'Creative Director & Design Lead',
    titleAr: 'مدير إبداعي ورئيس تصميم',
    category: 'creative',
    description: 'Artistic, refined aesthetic with minimal gallery architecture and cinematic moody lighting.',
    descriptionAr: 'طراز إبداعي أنيق مع معمار معارض حديث وإضاءة سينمائية ساحرة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-black-turtleneck-blazer',
    recommendedBackground: 'bg-minimal-art-gallery',
    lightingSetup: 'Softbox Key + Rim',
    tags: ['Design', 'Creative', 'Art Director', 'Architect'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'keynote-speaker-ted',
    title: 'Global Keynote Speaker',
    titleAr: 'متحدث رئيسي في المؤتمرات العالمية',
    category: 'academic',
    description: 'Dynamic stage speaker headshot with soft auditorium background lighting and confident posture.',
    descriptionAr: 'صورة شخصية ديناميكية للمتحدثين أمام مسرح المؤتمرات.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-charcoal-suit',
    recommendedBackground: 'bg-stage-auditorium',
    lightingSetup: 'Butterfly Beauty',
    tags: ['Speaker', 'TED', 'Author', 'Conference'],
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'vogue-editorial-fashion',
    title: 'Vogue & GQ Fashion Editorial',
    titleAr: 'بورتريه تحريري غلاف مجلات الموضة',
    category: 'editorial',
    description: 'High-fashion studio portrait with high contrast, dramatic shadows, and magazine cover aesthetic.',
    descriptionAr: 'بورتريه استوديو راقي بمستوى أغطية المجلات العالمية مع تباين درامي.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-luxury-tuxedo',
    recommendedBackground: 'bg-studio-dramatic-black',
    lightingSetup: 'Split Studio',
    tags: ['Fashion', 'Vogue', 'GQ', 'Editorial'],
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    popular: true,
  },
  {
    id: 'university-dean-professor',
    title: 'University Dean & Senior Scholar',
    titleAr: 'عميد جامعة وأستاذ أكاديمي',
    category: 'academic',
    description: 'Intellectual scholar portrait with historic university stone arcade and oak book stacks.',
    descriptionAr: 'بورتريه أكاديمي أمام أروقة الجامعة التاريخية والمكتبات الخشبية.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-tweed-jacket',
    recommendedBackground: 'bg-oxford-university-arch',
    lightingSetup: 'Natural Window',
    tags: ['Professor', 'Dean', 'Academia', 'Scholar'],
    image: 'https://images.unsplash.com/photo-1534751516642-a171e2616676?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'real-estate-mogul',
    title: 'Luxury Real Estate Agent & Developer',
    titleAr: 'خبير ومطور العقارات الفاخرة',
    category: 'corporate',
    description: 'Opulent real estate advisor portrait with architectural penthouse terrace glass view.',
    descriptionAr: 'صورة مستشار عقارات فاخرة أمام بنتهاوس حديث مع إطلالة مدينة زجاجية.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-beige-cream-blazer',
    recommendedBackground: 'bg-luxury-penthouse-terrace',
    lightingSetup: '3-Point Rembrandt',
    tags: ['Real Estate', 'Realtor', 'Developer', 'Luxury Property'],
    image: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cybersecurity-architect',
    title: 'Cybersecurity Chief & Cloud Lead',
    titleAr: 'رئيس الأمن السيبراني وهندسة السحاب',
    category: 'tech',
    description: 'Focused tech strategist in dark moody server room illumination with sharp eye light.',
    descriptionAr: 'خبير أمن سيبراني بإضاءة استوديو زرقاء داكنة مركزة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-black-turtleneck-blazer',
    recommendedBackground: 'bg-datacenter-neon-blue',
    lightingSetup: 'Split Studio',
    tags: ['Cybersecurity', 'Cloud', 'DevOps', 'Security'],
    image: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'diplomat-ambassador',
    title: 'United Nations Diplomat & Envoy',
    titleAr: 'دبلوماسي وسفير دولي',
    category: 'c-suite',
    description: 'Distinguished statesman or envoy with international flag gallery or marble embassy hall.',
    descriptionAr: 'بورتريه دبلوماسي وسفير رفيع أمام قاعة الرخام للسفارة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-executive-navy-suit',
    recommendedBackground: 'bg-embassy-marble-hall',
    lightingSetup: 'Butterfly Beauty',
    tags: ['Diplomat', 'Ambassador', 'Government', 'Statesman'],
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'hollywood-red-carpet',
    title: 'Hollywood Red Carpet & Celebrity',
    titleAr: 'نجوم السجادة الحمراء والسينما',
    category: 'lifestyle',
    description: 'Glamorous event headshot with soft studio flash flares and red carpet velvet backdrop.',
    descriptionAr: 'صورة شخصية هوليوودية متألقة بإضاءة الاستوديو الفاخرة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-luxury-tuxedo',
    recommendedBackground: 'bg-hollywood-red-carpet',
    lightingSetup: 'Butterfly Beauty',
    tags: ['Celebrity', 'Hollywood', 'Red Carpet', 'Gala'],
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'biotech-researcher-phd',
    title: 'Biotech Scientist & Innovation Director',
    titleAr: 'عالم تقنية حيوية ومدير أبحاث',
    category: 'healthcare',
    description: 'Intelligent, forward-looking scientist with high-tech lab equipment bokeh background.',
    descriptionAr: 'صورة عالم معملي أمام خلفية معمل أبحاث حيوية حديث.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-doctor-labcoat',
    recommendedBackground: 'bg-biotech-lab',
    lightingSetup: 'Natural Window',
    tags: ['Scientist', 'Biotech', 'PhD', 'Innovation'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'luxury-yacht-owner',
    title: 'Luxury Riviera & Yacht Club Captain',
    titleAr: 'أناقة نادي اليخوت والريبيرة',
    category: 'lifestyle',
    description: 'Sunkissed luxury portrait with azure Mediterranean sea, yacht deck mahogany, and golden hour lighting.',
    descriptionAr: 'إطلالة فاخرة مستوحاة من ريفيرا الفرنسية ونادي اليخوت على شاطئ البحر.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-linen-blazer-white',
    recommendedBackground: 'bg-mediterranean-yacht',
    lightingSetup: 'Natural Window',
    tags: ['Yacht', 'Luxury', 'Riviera', 'Mediterranean'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'tokyo-neon-futurist',
    title: 'Tokyo Futurist & AI Visionary',
    titleAr: 'رؤية مستقبلية - طوكيو التقنية',
    category: 'editorial',
    description: 'Cyberpunk-infused modern professional headshot with subtle ambient Tokyo lights.',
    descriptionAr: 'طراز تقني مستقبلي مع إضاءات طوكيو الملونة الهادئة.',
    gender: 'unisex',
    recommendedOutfit: 'outfit-black-turtleneck-blazer',
    recommendedBackground: 'bg-tokyo-ginza-lights',
    lightingSetup: 'Softbox Key + Rim',
    tags: ['Tokyo', 'Futurist', 'AI', 'Cyberpunk'],
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
  }
];
